version: '3.7'
# Put all your services here
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache-certbot

    volumes:
      - ./certs:/etc/letsencrypt
    restart: always
    network_mode: host

